### ISSUE TITLE
Add nbqa to pre-commit

### ISSUE THREAD

**Issue by adamgayoso** [scverse/cookiecutter-scverse#141]
Something like this work:

```
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.6.1
    hooks:
      - id: nbqa-pyupgrade
        args: [--py38-plus]
      - id: nbqa-black
      - id: nbqa-isort
      - id: nbqa-ruff
        args: [--fix]
      - id: nbqa
        entry: nbqa blacken-docs
        name: nbqa-blacken-docs
        alias: nbqa-blacken-docs
        additional_dependencies: [blacken-docs]
        args: [--nbqa-md]
      - id: nbqa
        entry: nbqa mdformat
        name: nbqa-mdformat
        alias: nbqa-mdformat
        additional_dependencies:
          [
            mdformat,
            mdformat-black,
            mdformat-frontmatter,
            mdformat-web,
            mdformat-myst,
          ]
        args: [--nbqa-md]
```

This would also be a good to do when switching to ruff as it will read configs in the toml

**Comment by adamgayoso** [comment]
So with ruff we can drop isort here. I found mdformat to be helpful

**Comment by flying-sheep** [comment]
pyupgrade too. so:

```
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.6.1
    hooks:
      - id: nbqa-black
      - id: nbqa-ruff
        args: [--fix]
      - id: nbqa
        entry: nbqa blacken-docs
        name: nbqa-blacken-docs
        alias: nbqa-blacken-docs
        additional_dependencies: [blacken-docs]
        args: [--nbqa-md]
      - id: nbqa
        entry: nbqa mdformat
        name: nbqa-mdformat
        alias: nbqa-mdformat
        additional_dependencies:
          - mdformat
          - mdformat-black
          - mdformat-frontmatter
          - mdformat-web
          - mdformat-myst
        args: [--nbqa-md]
```
