### ISSUE TITLE
Validate RST docstrings

### ISSUE THREAD

**Issue by flying-sheep** [scverse/cookiecutter-scverse#148]
Before switching to Ruff in #147, we used [flake8-rst-docstrings](https://github.com/peterjc/flake8-rst-docstrings), which hasn’t been implemented in Ruff at the time of writing. Me might want to consider a replacement.

```toml
rst-roles = ["class", "func", "ref", "cite:p", "cite:t"]
rst-directives = ["envvar", "exception"]
rst-substitutions = ["version"]
extend-ignore = ["RST307"]
```
