### ISSUE TITLE
Use SPDX in metadata

### ISSUE THREAD

**Issue by flying-sheep** [scverse/cookiecutter-scverse#325]
This line should be derived from the license choice:

https://github.com/scverse/cookiecutter-scverse/blob/0ed653c5570332539b7aadd359f1c398fd410aed/%7B%7Bcookiecutter.project_name%7D%7D/pyproject.toml#L10

With the outcome being

```toml
license = "MIT"
# or
license = "Apache-2.0"
```
